/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedCare;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author xyto_
 */
public class MedCare extends javax.swing.JFrame {

    /**
     * Creates new form Innovacion
     */
    public MedCare() {
        initComponents();
        
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Nombre_Paciente = new javax.swing.JLabel();
        jtf_Nombre_Paciente = new javax.swing.JTextField();
        jl_Apellido_Paciente = new javax.swing.JLabel();
        jtf_Apellido_Paciente = new javax.swing.JTextField();
        jl_Edad_Paciente = new javax.swing.JLabel();
        jtf_Edad_Paciente = new javax.swing.JTextField();
        jl_ID_Paciente = new javax.swing.JLabel();
        jtf_ID_Paciente = new javax.swing.JTextField();
        jl_Peso_Paciente = new javax.swing.JLabel();
        jl_Altura_Paciente = new javax.swing.JLabel();
        jl_DrAsignado_Paciente = new javax.swing.JLabel();
        jtf_Peso_Paciente = new javax.swing.JTextField();
        jtf_Altura_Paciente = new javax.swing.JTextField();
        jtf_DrAsignado_Paciente = new javax.swing.JTextField();
        jl_Medicamento_Paciente = new javax.swing.JLabel();
        jtf_Medicamento_Paciente = new javax.swing.JTextField();
        jl_FechaFinal_Paciente = new javax.swing.JLabel();
        jdc_FechaFinal_Paciente = new com.toedter.calendar.JDateChooser();
        jl_Rango_Paciente = new javax.swing.JLabel();
        jsp_Rango_Paciente = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jcb_Paciente = new javax.swing.JComboBox<>();
        jl_ListaPacientes_Paciente = new javax.swing.JLabel();
        jl_ImagenMedicamento_Paciente = new javax.swing.JLabel();
        jl_Correo_Paciente = new javax.swing.JLabel();
        jtf_Correo_Paciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MedCare");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jl_Nombre_Paciente.setText("Nombre");

        jl_Apellido_Paciente.setText("Apellido");

        jl_Edad_Paciente.setText("Edad");

        jl_ID_Paciente.setText("ID");

        jl_Peso_Paciente.setText("Peso");

        jl_Altura_Paciente.setText("Altura");

        jl_DrAsignado_Paciente.setText("Doctor Asignado");

        jl_Medicamento_Paciente.setText("Medicamento");

        jl_FechaFinal_Paciente.setText("Fecha final");

        jl_Rango_Paciente.setText("Rango de horas");

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jl_ListaPacientes_Paciente.setText("Pacientes");

        jl_ImagenMedicamento_Paciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_ImagenMedicamento_Paciente.setText("Insertar Imagen");
        jl_ImagenMedicamento_Paciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jl_ImagenMedicamento_Paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_ImagenMedicamento_PacienteMouseClicked(evt);
            }
        });

        jl_Correo_Paciente.setText("Correo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_ID_Paciente)
                        .addGap(51, 51, 51)
                        .addComponent(jtf_ID_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jl_ListaPacientes_Paciente)
                        .addGap(16, 16, 16)
                        .addComponent(jcb_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Peso_Paciente)
                                    .addComponent(jl_Altura_Paciente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_Peso_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_Altura_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_DrAsignado_Paciente)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_DrAsignado_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_Medicamento_Paciente)
                                .addGap(35, 35, 35)
                                .addComponent(jtf_Medicamento_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_FechaFinal_Paciente)
                                .addGap(49, 49, 49)
                                .addComponent(jdc_FechaFinal_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_Rango_Paciente)
                                .addGap(21, 21, 21)
                                .addComponent(jsp_Rango_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Nombre_Paciente)
                                    .addComponent(jl_Apellido_Paciente)
                                    .addComponent(jl_Edad_Paciente)
                                    .addComponent(jl_Correo_Paciente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_Nombre_Paciente)
                                    .addComponent(jtf_Apellido_Paciente)
                                    .addComponent(jtf_Edad_Paciente)
                                    .addComponent(jtf_Correo_Paciente, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                        .addGap(36, 36, 36)
                        .addComponent(jl_ImagenMedicamento_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jl_ID_Paciente))
                    .addComponent(jtf_ID_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jl_ListaPacientes_Paciente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jcb_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jl_ImagenMedicamento_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jl_Nombre_Paciente)
                                .addGap(24, 24, 24)
                                .addComponent(jl_Apellido_Paciente)
                                .addGap(24, 24, 24)
                                .addComponent(jl_Edad_Paciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtf_Nombre_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_Apellido_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_Edad_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Correo_Paciente)
                            .addComponent(jtf_Correo_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jl_Peso_Paciente)
                                .addGap(24, 24, 24)
                                .addComponent(jl_Altura_Paciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtf_Peso_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_Altura_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jl_DrAsignado_Paciente))
                            .addComponent(jtf_DrAsignado_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jl_Medicamento_Paciente))
                            .addComponent(jtf_Medicamento_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jl_FechaFinal_Paciente))
                            .addComponent(jdc_FechaFinal_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jl_Rango_Paciente))
                            .addComponent(jsp_Rango_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_ImagenMedicamento_PacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_ImagenMedicamento_PacienteMouseClicked
        // TODO add your handling code here:
        jl_ImagenMedicamento_Paciente.setText("");

        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
        fc.setFileFilter(filtro);

        File Archivo;
        int op = fc.showOpenDialog(this);

        if (op == JFileChooser.APPROVE_OPTION) {
            Archivo = fc.getSelectedFile();
            RutaImagen = Archivo.getPath();
            System.out.println(Archivo.getPath());
            Image Img = Toolkit.getDefaultToolkit().createImage(Archivo.getPath()).getScaledInstance(180, 229, 0);
            this.jl_ImagenMedicamento_Paciente.setIcon(new ImageIcon(Img));
        }
    }//GEN-LAST:event_jl_ImagenMedicamento_PacienteMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String ID, Nombre, Apellido, Correo, DrAsignado, Medicamento, Fecha;
        int Edad, RangoHoras;
        double Peso, Altura;
        
        Date FechaTemp = jdc_FechaFinal_Paciente.getDate();
        SimpleDateFormat Formato = new SimpleDateFormat("dd/MM/yyyy");
        Fecha = Formato.format(FechaTemp);
       
        ID = jtf_ID_Paciente.getText();
        Nombre = jtf_Nombre_Paciente.getText();
        Apellido = jtf_Apellido_Paciente.getText();
        Correo = jtf_Correo_Paciente.getText();
        DrAsignado = jtf_DrAsignado_Paciente.getText();
        Medicamento = jtf_Medicamento_Paciente.getText();
        Edad = Integer.parseInt(jtf_Edad_Paciente.getText());
        RangoHoras = Integer.parseInt(jsp_Rango_Paciente.getValue().toString());
        Peso = Double.parseDouble(jtf_Peso_Paciente.getText());
        Altura = Double.parseDouble(jtf_Altura_Paciente.getText());
        
        Paciente NuevoPaciente = new Paciente(Nombre, Apellido, Edad, ID, Correo, Peso, Altura, Medicamento, Peso, Fecha, DrAsignado, RutaImagen);
        Pacientes.add(NuevoPaciente);
        jcb_Paciente.addItem(NuevoPaciente);
        
        jtf_ID_Paciente.setText("");
        jtf_Nombre_Paciente.setText("");
        jtf_Apellido_Paciente.setText("");
        jtf_Correo_Paciente.setText("");
        jtf_DrAsignado_Paciente.setText("");
        jtf_Medicamento_Paciente.setText("");
        jtf_Edad_Paciente.setText("");
        jsp_Rango_Paciente.setValue(0);
        jtf_Peso_Paciente.setText("");
        jtf_Altura_Paciente.setText("");
        
        JOptionPane.showMessageDialog(this, "Paciente agreagado exitosamente", "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Guardar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedCare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Paciente> jcb_Paciente;
    private com.toedter.calendar.JDateChooser jdc_FechaFinal_Paciente;
    private javax.swing.JLabel jl_Altura_Paciente;
    private javax.swing.JLabel jl_Apellido_Paciente;
    private javax.swing.JLabel jl_Correo_Paciente;
    private javax.swing.JLabel jl_DrAsignado_Paciente;
    private javax.swing.JLabel jl_Edad_Paciente;
    private javax.swing.JLabel jl_FechaFinal_Paciente;
    private javax.swing.JLabel jl_ID_Paciente;
    private javax.swing.JLabel jl_ImagenMedicamento_Paciente;
    private javax.swing.JLabel jl_ListaPacientes_Paciente;
    private javax.swing.JLabel jl_Medicamento_Paciente;
    private javax.swing.JLabel jl_Nombre_Paciente;
    private javax.swing.JLabel jl_Peso_Paciente;
    private javax.swing.JLabel jl_Rango_Paciente;
    private javax.swing.JSpinner jsp_Rango_Paciente;
    private javax.swing.JTextField jtf_Altura_Paciente;
    private javax.swing.JTextField jtf_Apellido_Paciente;
    private javax.swing.JTextField jtf_Correo_Paciente;
    private javax.swing.JTextField jtf_DrAsignado_Paciente;
    private javax.swing.JTextField jtf_Edad_Paciente;
    private javax.swing.JTextField jtf_ID_Paciente;
    private javax.swing.JTextField jtf_Medicamento_Paciente;
    private javax.swing.JTextField jtf_Nombre_Paciente;
    private javax.swing.JTextField jtf_Peso_Paciente;
    // End of variables declaration//GEN-END:variables
    String RutaImagen = "";
    ArrayList<Paciente> Pacientes = new ArrayList();
    
    public void Guardar(){
        try {
            File archivo = null;
            try {
                archivo = new File("./Binary.AOC");
                FileOutputStream fo = new FileOutputStream(archivo);
                ObjectOutputStream oo = new ObjectOutputStream(fo);
                oo.writeObject(Pacientes);
                oo.close();
                fo.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se guardo correctamente",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se guardo correctamente",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void Cargar(){
        try {
            File archivo = null;
            try {
                archivo = new File("./Binary.AOC");
                FileInputStream fo = new FileInputStream(archivo);
                ObjectInputStream oo = new ObjectInputStream(fo);
                Pacientes = (ArrayList<Paciente>) oo.readObject();

                for (int i = 0; i < Pacientes.size(); i++) {
                    jcb_Paciente.addItem(Pacientes.get(i));
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No hay archivo guardado",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se cargo el archivo",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
}
