/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedCare;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;

/**
 *
 * @author xyto_
 */
public class MedCare extends javax.swing.JFrame {

    /**
     * Creates new form Innovacion
     */
    public MedCare() {
        initComponents();
        setLocationRelativeTo(this);
        
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Enviar = new javax.swing.JDialog();
        jl_Correo_Doctor = new javax.swing.JLabel();
        jl_titulo_Doctor = new javax.swing.JLabel();
        jl_Password_Doctor = new javax.swing.JLabel();
        jb_Enviar_Doctor = new javax.swing.JButton();
        jtf_Correo_Doctor = new javax.swing.JTextField();
        jtf_Password_Doctor = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jl_ImagenMedicamento_Paciente = new javax.swing.JLabel();
        jl_ListaPacientes_Paciente = new javax.swing.JLabel();
        jcb_Paciente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jl_Nombre_Paciente = new javax.swing.JLabel();
        jtf_Nombre_Paciente = new javax.swing.JTextField();
        jl_Apellido_Paciente = new javax.swing.JLabel();
        jtf_Apellido_Paciente = new javax.swing.JTextField();
        jl_ID_Paciente = new javax.swing.JLabel();
        jtf_ID_Paciente = new javax.swing.JTextField();
        jl_Edad_Paciente = new javax.swing.JLabel();
        jtf_Edad_Paciente = new javax.swing.JTextField();
        jl_Correo_Paciente = new javax.swing.JLabel();
        jtf_Correo_Paciente = new javax.swing.JTextField();
        jl_Peso_Paciente = new javax.swing.JLabel();
        jtf_Peso_Paciente = new javax.swing.JTextField();
        jl_Altura_Paciente = new javax.swing.JLabel();
        jtf_Altura_Paciente = new javax.swing.JTextField();
        jl_DrAsignado_Paciente = new javax.swing.JLabel();
        jtf_DrAsignado_Paciente = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jl_Medicamento_Paciente = new javax.swing.JLabel();
        jtf_Medicamento_Paciente = new javax.swing.JTextField();
        jl_Rango_Paciente = new javax.swing.JLabel();
        jsp_Rango_Paciente = new javax.swing.JSpinner();
        jl_FechaFinal_Paciente = new javax.swing.JLabel();
        jdc_FechaFinal_Paciente = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jd_Enviar.setTitle("SEND MESSAGE");

        jl_Correo_Doctor.setText("Correo electronico");

        jl_titulo_Doctor.setText("Doctor Asignado");

        jl_Password_Doctor.setText("Contraseña");

        jb_Enviar_Doctor.setText("Enviar");
        jb_Enviar_Doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_Enviar_DoctorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_EnviarLayout = new javax.swing.GroupLayout(jd_Enviar.getContentPane());
        jd_Enviar.getContentPane().setLayout(jd_EnviarLayout);
        jd_EnviarLayout.setHorizontalGroup(
            jd_EnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EnviarLayout.createSequentialGroup()
                .addGroup(jd_EnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_EnviarLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jl_titulo_Doctor))
                    .addGroup(jd_EnviarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jd_EnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Correo_Doctor)
                            .addComponent(jl_Password_Doctor))
                        .addGap(48, 48, 48)
                        .addGroup(jd_EnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Correo_Doctor)
                            .addComponent(jtf_Password_Doctor))))
                .addContainerGap())
            .addGroup(jd_EnviarLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jb_Enviar_Doctor)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jd_EnviarLayout.setVerticalGroup(
            jd_EnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EnviarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jl_titulo_Doctor)
                .addGap(26, 26, 26)
                .addGroup(jd_EnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Correo_Doctor)
                    .addComponent(jtf_Correo_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_EnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Password_Doctor)
                    .addComponent(jtf_Password_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jb_Enviar_Doctor)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MedCare");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(76, 107, 136));

        jButton1.setBackground(new java.awt.Color(254, 143, 124));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jl_ImagenMedicamento_Paciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_ImagenMedicamento_Paciente.setText("Insertar Imagen");
        jl_ImagenMedicamento_Paciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jl_ImagenMedicamento_Paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_ImagenMedicamento_PacienteMouseClicked(evt);
            }
        });

        jl_ListaPacientes_Paciente.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jl_ListaPacientes_Paciente.setForeground(new java.awt.Color(255, 255, 255));
        jl_ListaPacientes_Paciente.setText("Pacientes");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Informacion Paciente");

        jPanel3.setBackground(new java.awt.Color(201, 213, 225));

        jl_Nombre_Paciente.setText("Nombre");

        jl_Apellido_Paciente.setText("Apellido");

        jtf_Apellido_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Apellido_PacienteActionPerformed(evt);
            }
        });

        jl_ID_Paciente.setText("ID");

        jl_Edad_Paciente.setText("Edad");

        jl_Correo_Paciente.setText("Correo");

        jl_Peso_Paciente.setText("Peso");

        jl_Altura_Paciente.setText("Altura");

        jl_DrAsignado_Paciente.setText("Doctor Asignado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_Nombre_Paciente)
                    .addComponent(jl_Apellido_Paciente)
                    .addComponent(jl_ID_Paciente)
                    .addComponent(jl_Edad_Paciente)
                    .addComponent(jl_Correo_Paciente)
                    .addComponent(jtf_Correo_Paciente, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jtf_Edad_Paciente)
                    .addComponent(jtf_ID_Paciente)
                    .addComponent(jtf_Apellido_Paciente)
                    .addComponent(jtf_Nombre_Paciente)
                    .addComponent(jl_Peso_Paciente)
                    .addComponent(jtf_Peso_Paciente)
                    .addComponent(jl_Altura_Paciente)
                    .addComponent(jtf_Altura_Paciente)
                    .addComponent(jl_DrAsignado_Paciente)
                    .addComponent(jtf_DrAsignado_Paciente))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jl_Nombre_Paciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_Nombre_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_Apellido_Paciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_Apellido_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_ID_Paciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_ID_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_Edad_Paciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_Edad_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_Correo_Paciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_Correo_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_Peso_Paciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_Peso_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_Altura_Paciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_Altura_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_DrAsignado_Paciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_DrAsignado_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(34, 201, 220));

        jl_Medicamento_Paciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_Medicamento_Paciente.setText("Medicamento");

        jl_Rango_Paciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_Rango_Paciente.setText("Rango de horas");

        jl_FechaFinal_Paciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_FechaFinal_Paciente.setText("Fecha final");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Medicamento_Paciente)
                    .addComponent(jtf_Medicamento_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Rango_Paciente)
                    .addComponent(jsp_Rango_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_FechaFinal_Paciente)
                    .addComponent(jdc_FechaFinal_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jl_Medicamento_Paciente)
                .addGap(18, 18, 18)
                .addComponent(jtf_Medicamento_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jl_Rango_Paciente)
                .addGap(18, 18, 18)
                .addComponent(jsp_Rango_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jl_FechaFinal_Paciente)
                .addGap(31, 31, 31)
                .addComponent(jdc_FechaFinal_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Informacion Medicamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_ListaPacientes_Paciente)
                                .addGap(26, 26, 26)
                                .addComponent(jcb_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_ImagenMedicamento_Paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ListaPacientes_Paciente)
                    .addComponent(jcb_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jl_ImagenMedicamento_Paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(201, 213, 225));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 143, 124));
        jLabel2.setText("Recordatorio de Medicamentos");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1497519943_heart.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_ImagenMedicamento_PacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_ImagenMedicamento_PacienteMouseClicked
        // TODO add your handling code here:
        jl_ImagenMedicamento_Paciente.setText("");

        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
        fc.setFileFilter(filtro);

        File Archivo;
        int op = fc.showOpenDialog(this);

        if (op == JFileChooser.APPROVE_OPTION) {
            Archivo = fc.getSelectedFile();
            RutaImagen = Archivo.getPath();
            System.out.println(Archivo.getPath());
            Image Img = Toolkit.getDefaultToolkit().createImage(Archivo.getPath()).getScaledInstance(180, 229, 0);
            this.jl_ImagenMedicamento_Paciente.setIcon(new ImageIcon(Img));
        }
    }//GEN-LAST:event_jl_ImagenMedicamento_PacienteMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String ID, Nombre, Apellido, Correo, DrAsignado, Medicamento, Fecha;
        int Edad, RangoHoras;
        double Peso, Altura;

        Date FechaTemp = jdc_FechaFinal_Paciente.getDate();
        SimpleDateFormat Formato = new SimpleDateFormat("dd/MM/yyyy");
        Fecha = Formato.format(FechaTemp);

        ID = jtf_ID_Paciente.getText();
        Nombre = jtf_Nombre_Paciente.getText();
        Apellido = jtf_Apellido_Paciente.getText();
        Correo = jtf_Correo_Paciente.getText();
        DrAsignado = jtf_DrAsignado_Paciente.getText();
        Medicamento = jtf_Medicamento_Paciente.getText();
        Edad = Integer.parseInt(jtf_Edad_Paciente.getText());
        RangoHoras = Integer.parseInt(jsp_Rango_Paciente.getValue().toString());
        Peso = Double.parseDouble(jtf_Peso_Paciente.getText());
        Altura = Double.parseDouble(jtf_Altura_Paciente.getText());

        Paciente NuevoPaciente = new Paciente(Nombre, Apellido, Edad, ID, Correo, Peso, Altura, Medicamento, Peso, Fecha, DrAsignado, RutaImagen);
        Pacientes.add(NuevoPaciente);
        jcb_Paciente.addItem(NuevoPaciente);

        jtf_ID_Paciente.setText("");
        jtf_Nombre_Paciente.setText("");
        jtf_Apellido_Paciente.setText("");
        jtf_Correo_Paciente.setText("");
        jtf_DrAsignado_Paciente.setText("");
        jtf_Medicamento_Paciente.setText("");
        jtf_Edad_Paciente.setText("");
        jsp_Rango_Paciente.setValue(0);
        jtf_Peso_Paciente.setText("");
        jtf_Altura_Paciente.setText("");
        jl_ImagenMedicamento_Paciente.setDisabledIcon(null);

        JOptionPane.showMessageDialog(this, "Paciente agreagado exitosamente", "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);

        jd_Enviar.setModal(true);
        jd_Enviar.pack();
        jd_Enviar.setLocationRelativeTo(this);
        jd_Enviar.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Guardar();
    }//GEN-LAST:event_formWindowClosing

    private void jb_Enviar_DoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_Enviar_DoctorMouseClicked
        // TODO add your handling code here:
        Username = jtf_Correo_Doctor.getText();
        Password = jtf_Password_Doctor.getText();

        To = Pacientes.get(Pacientes.size() - 1).getCorreo();
        Subject = "Recordatorio Medicamentos";
        Mensaje = "Tomar " + Pacientes.get(Pacientes.size() - 1).getMedicamento() + " cada " + Pacientes.get(Pacientes.size() - 1).getRango() + " horas " + " hasta "
                + Pacientes.get(Pacientes.size() - 1).getFechaFinal();

        SendMail();
        jtf_Correo_Doctor.setText("");
        jtf_Password_Doctor.setText("");
    }//GEN-LAST:event_jb_Enviar_DoctorMouseClicked

    private void jtf_Apellido_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Apellido_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Apellido_PacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedCare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jb_Enviar_Doctor;
    private javax.swing.JComboBox<Paciente> jcb_Paciente;
    private javax.swing.JDialog jd_Enviar;
    private com.toedter.calendar.JDateChooser jdc_FechaFinal_Paciente;
    private javax.swing.JLabel jl_Altura_Paciente;
    private javax.swing.JLabel jl_Apellido_Paciente;
    private javax.swing.JLabel jl_Correo_Doctor;
    private javax.swing.JLabel jl_Correo_Paciente;
    private javax.swing.JLabel jl_DrAsignado_Paciente;
    private javax.swing.JLabel jl_Edad_Paciente;
    private javax.swing.JLabel jl_FechaFinal_Paciente;
    private javax.swing.JLabel jl_ID_Paciente;
    private javax.swing.JLabel jl_ImagenMedicamento_Paciente;
    private javax.swing.JLabel jl_ListaPacientes_Paciente;
    private javax.swing.JLabel jl_Medicamento_Paciente;
    private javax.swing.JLabel jl_Nombre_Paciente;
    private javax.swing.JLabel jl_Password_Doctor;
    private javax.swing.JLabel jl_Peso_Paciente;
    private javax.swing.JLabel jl_Rango_Paciente;
    private javax.swing.JLabel jl_titulo_Doctor;
    private javax.swing.JSpinner jsp_Rango_Paciente;
    private javax.swing.JTextField jtf_Altura_Paciente;
    private javax.swing.JTextField jtf_Apellido_Paciente;
    private javax.swing.JTextField jtf_Correo_Doctor;
    private javax.swing.JTextField jtf_Correo_Paciente;
    private javax.swing.JTextField jtf_DrAsignado_Paciente;
    private javax.swing.JTextField jtf_Edad_Paciente;
    private javax.swing.JTextField jtf_ID_Paciente;
    private javax.swing.JTextField jtf_Medicamento_Paciente;
    private javax.swing.JTextField jtf_Nombre_Paciente;
    private javax.swing.JPasswordField jtf_Password_Doctor;
    private javax.swing.JTextField jtf_Peso_Paciente;
    // End of variables declaration//GEN-END:variables
    String RutaImagen = "", Username = "", Password = "", To = "", Subject = "", Mensaje = "";
    ArrayList<Paciente> Pacientes = new ArrayList();

    public void Guardar() {
        try {
            File archivo = null;
            try {
                archivo = new File("./Binary.AOC");
                FileOutputStream fo = new FileOutputStream(archivo);
                ObjectOutputStream oo = new ObjectOutputStream(fo);
                oo.writeObject(Pacientes);
                oo.close();
                fo.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se guardo correctamente",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se guardo correctamente",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Cargar() {
        try {
            File archivo = null;
            try {
                archivo = new File("./Binary.AOC");
                FileInputStream fo = new FileInputStream(archivo);
                ObjectInputStream oo = new ObjectInputStream(fo);
                Pacientes = (ArrayList<Paciente>) oo.readObject();

                for (int i = 0; i < Pacientes.size(); i++) {
                    jcb_Paciente.addItem(Pacientes.get(i));
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No hay archivo guardado",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se cargo el archivo",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void SendMail() {
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(Username, Password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(Username));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(To));
            message.setSubject(Subject);
            message.setText(Mensaje);
            
            
            Multipart multipart = new MimeMultipart();
            MimeBodyPart textBodyPart = new MimeBodyPart();
            textBodyPart.setText("Tomar el Medicamento!");
            
            File archivo = new File(RutaImagen);
            
            MimeBodyPart attachmentBodyPart= new MimeBodyPart();
            DataSource source = new FileDataSource(archivo); // ex : "C:\\test.pdf"
            attachmentBodyPart.setDataHandler(new DataHandler(source));
            attachmentBodyPart.setFileName("Pastilla.jpg"); // ex : "test.pdf"

            multipart.addBodyPart(textBodyPart);  // add the text part
            multipart.addBodyPart(attachmentBodyPart); // add the attachement part

            message.setContent(multipart);
            /*
           Transport transport=mailSession.getTransport("smtp");
           transport.connect(host, user, pass);
           transport.sendMessage(msg, msg.getAllRecipients());
           transport.close();
            */
            
            

            Transport.send(message);
            JOptionPane.showMessageDialog(this, "Su mensaje ha sido enviado", "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }
}
